# Generated by Django 2.1.1 on 2018-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20181119_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deal_date',
            field=models.DateField(blank=True, null=True, verbose_name='报名时间'),
        ),
    ]
